#!/bin/bash

# ==========================================================================
# Custom pre-commit git hook
# Requirements :
#           - tflint : source => https://github.com/terraform-linters/tflint
# ==========================================================================
# Features:
#   - Terraform :
#       - EOF newline checks
#       - terraform fmt
#       - tflint
# ==========================================================================

ROOT_DIR=$(git rev-parse --show-toplevel)
RED='\033[1;31m'
GREEN='\033[1;32m'
ORANGE='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color

# =========================
# Terraform specific checks
# =========================
function _terraform() {
    echo -e "${BLUE}[PRECOMMIT]${NC} Checking for EOF newline"
    for TF_FILE in $1; do
        if [ "$(tail -c 1 "${TF_FILE}")" != "" ]; then
            echo -e "${TF_FILE} is missing EOF newline"
            exit 1
        fi
    done

    TF_DIRS=$(echo -e "$1" | sed -E 's|/[^/]+$|/|' | uniq)

    echo -e "${BLUE}[PRECOMMIT]${NC} Running 'terraform fmt' and tflint"
    for TF_DIR in $TF_DIRS; do
        if ! output="$(terraform fmt -recursive -diff --check "${TF_DIR}")"; then
            echo -e "${RED}[ERROR]${NC}${ORANGE}[FMT]${NC} ${TF_DIR} => ${output}"
            exit 1
        else
         echo -e "${GREEN}[SUCCESS]${NC}${GREEN}[FMT]${NC} ${TF_DIR} No fmt errors detected." 
        fi
        if ! tfvar="$(ls ${TF_DIR} | grep -qs 'tfvars')"; then
          if ! output="$(cd "${TF_DIR}" && tflint .)"; then
              echo -e "${RED}[ERROR]${NC}${ORANGE}[TFLINT]${NC} ${TF_DIR} => ${output}"
              exit 1
          else
            echo -e "${GREEN}[SUCCESS]${NC}${GREEN}[FMT]${NC} ${TF_DIR} No lint errors detected."
          fi
        fi
    done
}

# TF_FILES=$(fd -H -p --type=f "\.(tf(vars)?)$" --exclude ".terraform" "${ROOT_DIR}")
TF_FILES=$(git status --porcelain=1 | grep -E '^A|^M' | grep -E '\.(tf(vars)?)$' | awk '{print $2}' | grep -v '.terraform/')

if [ -n "${TF_FILES}" ]; then
    echo -e "${BLUE}[PRECOMMIT]${NC} Terraform checks ..."
    _terraform "$TF_FILES"
else
    echo -e "${BLUE}[PRECOMMIT]${NC} No staged Terraform files"
fi
